export const TOGGLE_LOADING = 'TOGGLE_LOADING'
export const STORAGE_INPUT_VALUE = 'STORAGE_INPUT_VALUE'
export const CLEAR_INPUT_VALUE = 'CLEAR_INPUT_VALUE'
export const SWITCH_SEARCH_API = 'SWITCH_SEARCH_API'

export const INIT_TAB_BAR = 'INIT_TAB_BAR'

export const SWITCH_MOVIE_TAB = 'SWITCH_MOVIE_TAB'
export const CACHE_MOVIE_TAB = 'CACHE_MOVIE_TAB'
export const RECOVER_MOVIE_TAB = 'RECOVER_MOVIE_TAB'
export const MOVIE_TAB_STYLE = 'MOVIE_TAB_STYLE'
export const DISABLE_SCROLL = 'DISABLE_SCROLL'

export const GET_MOVIES_REQUEST = 'GET_MOVIES_REQUEST'
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS'
export const GET_MOVIES_FAILURE = 'GET_MOVIES_FAILURE'

export const TOGGLE_INPUT_CLEAR = 'TOGGLE_INPUT_CLEAR'
