export const TOGGLE_LOADING = 'TOGGLE_LOADING';
export const STORAGE_INPUT_VALUE = 'STORAGE_INPUT_VALUE';
export const CLEAR_INPUT_VALUE = 'CLEAR_INPUT_VALUE';
export const SWITCH_SEARCH_API = 'SWITCH_SEARCH_API';

export const INIT_TAB_BAR = 'INIT_TAB_BAR';

export const SWITCH_MOVIE_TAB = 'SWITCH_MOVIE_TAB';
export const CACHE_MOVIE_TAB = 'CACHE_MOVIE_TAB';
export const RECOVER_MOVIE_TAB = 'RECOVER_MOVIE_TAB';
export const MOVIE_TAB_STYLE = 'MOVIE_TAB_STYLE';
export const DISABLE_SCROLL = 'DISABLE_SCROLL';

export const CHANGE_LOAD_TXT = 'CHANGE_LOAD_TXT';
export const GET_MOVIES_REQUEST = 'GET_MOVIES_REQUEST';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIES_FAILURE = 'GET_MOVIES_FAILURE';

export const TOGGLE_INPUT_CLEAR = 'TOGGLE_INPUT_CLEAR';

export const GET_DETAIL_REQUEST = 'GET_DETAIL_REQUEST';
export const GET_DETAIL_SUCCESS = 'GET_DETAIL_SUCCESS';
export const GET_DETAIL_FAILURE = 'GET_DETAIL_FAILURE';
export const INIT_COLLECT_STATUS = 'INIT_COLLECT_STATUS';
export const COLLECT_MOVIE_ADD = 'COLLECT_MOVIE_ADD';
export const COLLECT_MOVIE_DELETE = 'COLLECT_MOVIE_DELETE';

export const GET_CELEBRITY_REQUEST = 'GET_CELEBRITY_REQUEST';
export const GET_CELEBRITY_SUCCESS = 'GET_CELEBRITY_SUCCESS';
export const GET_CELEBRITY_FAILURE = 'GET_CELEBRITY_FAILURE';

